# Generated by Django 5.2.7 on 2025-11-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('provider_name_code', models.CharField(help_text="The code name RiskPay uses, e.g., 'simplex'", max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('account_number', models.CharField(blank=True, help_text='Your account number with this provider, if any.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this provider on the frontend.')),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='The fee percentage, e.g., 12.00 for 12%', max_digits=5)),
                ('type', models.CharField(choices=[('CRYPTO', 'Crypto'), ('FIAT', 'Fiat Gateway')], default='FIAT', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
            ],
        ),
    ]
