# Generated by Django 5.2.7 on 2025-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Markdown or text instructions for bank transfer.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='type',
            field=models.CharField(choices=[('CRYPTO', 'Crypto'), ('FIAT', 'Fiat Gateway'), ('BANK_TRANSFER', 'Manual Bank Transfer')], default='FIAT', max_length=20),
        ),
    ]
