# Generated by Django 5.2.7 on 2025-11-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quoterequest'),
        ),
    ]
