# Generated by Django 5.2.7 on 2025-11-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('ecommerce', '0006_alter_order_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_gateway_charge_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_ipn_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_name',
            field=models.CharField(default='RiskPay', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_payment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_payment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.milestone'),
        ),
    ]
