# Generated by Django 5.2.7 on 2025-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_transaction_payment_gateway_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('AWAITING_PAYMENT', 'Awaiting Payment')], default='PENDING', max_length=20),
        ),
    ]
