# Generated by Django 5.2.7 on 2025-11-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_negotiated_price_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gateway_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gateway_payment_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gateway_payment_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_address_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_coin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_polygon_address_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_txid_out',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_value_in_coin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_name',
            field=models.CharField(blank=True, default='RiskPay', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_ipn_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
