# Generated by Django 5.2.7 on 2025-11-22 18:36

import ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_transaction_gateway_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proof_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.models.transaction_proof_path),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('VERIFYING', 'Verifying Proof')], default='PENDING', max_length=20),
        ),
    ]
