# Generated by Django 5.2.7 on 2025-11-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('site_location', models.TextField(blank=True, null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
